
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/online-shop
    username: root
    password: root

  output:
    ansi:
      enabled: always
jwt:
  access:
    token:
      expires: '60000'
  refresh:
    token:
      expires: '1500000'
  secret: 990f8b020d66cb200e21182998c5723d575d9ad502278e4dec6f3913905743af

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none

  flyway:
    locations: classpath:db/migration, db/dev
    enabled: true

---
logging:
  level:
    org:
      springframework:
        web: DEBUG
        orm:
          jpa: DEBUG
          transaction: DEBUG
    com:
      k0s: DEBUG

spring:
  config:
    activate:
      on-profile: test

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    locations: classpath:db/migration, db/test
    enabled: false

---

spring:
  config:
    activate:
      on-profile: heroku

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: testcontainers

  datasource:
    url: jdbc:tc:postgresql:latest://db




